<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
  <meta name="robots" content="index, follow" />
  <meta name="keywords" content="Fernando de Souza" />
  <meta name="title" content="Página Pessoal Fernando de Souza" />
  <meta name="description" content="" />
<title>Fernando de Souza</title>
<!-- ////////////////////////////////// -->
<!-- //      Start Stylesheets       // -->
<!-- ////////////////////////////////// -->
<link href="css/style.css" type="text/css" rel="stylesheet" />
<link href="css/slimbox2.css" type="text/css" rel="stylesheet" />
<!-- ////////////////////////////////// -->
<!-- //      Javascript Files        // -->
<!-- ////////////////////////////////// -->
<script type="text/javascript" src="js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="js/jquery.cycle.all.min.js"></script>
<script type="text/javascript">
  $(function() {
    $('#maincontent').cycle({
        fx:     'scrollHorz', // You can choose effect do you like, for reference : http://www.malsup.com/jquery/cycle/browser.html
        speed:  'slow',
        timeout: 0,
        pager:  '#nav',
        pagerAnchorBuilder: function(idx, slide) {
            // return sel string for existing anchor
            return '#nav li:eq(' + (idx) + ') a';
        }
    });
});
</script>
<script type="text/javascript">
   $(function(){     
        $('#work').cycle({
            timeout: 0,  // milliseconds between slide transitions (0 to disable auto advance)			
            fx:      'fade', // choose your transition type, ex: fade, scrollUp, shuffle, etc...
			next: 	 '#next',
			prev:    '#prev'			    
        });				         
     });
</script>

<script type="text/javascript" src="js/slimbox2.js"></script>
<script type="text/javascript" src="js/contact.js"></script>
<!--[if IE 6]>
    <script type="text/javascript" src="js/dd_belated_png.js"></script>
	<script>DD_belatedPNG.fix('#bg-content-repeat1, #bg-content-repeat2, #bg-content-top, #bg-content-bottom');</script>
<![endif]-->
</head>
<body>

<div id="container">
	<div id="content">
		<div id="bg-content-top"></div><!-- end bg-content-top -->
		<div id="bg-content-repeat1">
		<div id="bg-content-repeat2">
			<div id="main">
				<div id="top">
					
					<div id="logo">
						<h1>
							Fernando de Souza
						</h1>
					</div>

					<div id="navtop">
						<ul id="nav">
							<li class="nav1"><a href="#" title="homepage"></a></li>
							<li class="nav2"><a href="#" title="about"></a></li>
							<li class="nav3"><a href="#" title="work"></a></li>
							<li class="nav4"><a href="#" title="social network"></a></li>
							<li class="nav5"><a href="#" title="contact"></a></li>
						</ul>
					</div><!-- end nav -->
					<div class="clr"></div><!-- clear float -->
				</div><!-- end top -->
				<div id="maincontent">
					<div class="page"><!-- HOMEPAGE -->
					<h1>Seja bem-vindo</h1>
					<p><img src="images/img.jpg" alt="" class="imgleft" />Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quisquam est.</p>
					<p>Curabitur iaculis eros vestibulum odio placerat rutrum. Integer hendrerit bibendum enim, non congue erat posuere ut. Nullam auctor posuere eros sit amet blandit. In purus metus, elementum vel ultricies sit amet, condimentum quis nisi.</p><p> Morbi commodo cursus velit eget euismod. Sed libero elit, blandit quis aliquam sed, ultricies ultrices neque. Etiam accumsan porta nisi, ac vulputate quam posuere non. Suspendisse hendrerit molestie mi consectetur aliquam.</p>
					</div><!-- END HOMEPAGE -->

					<div class="page"><!-- ABOUT US PAGE -->
						<h1>Sobre mim</h1>
						<img src="images/people.jpg" alt="" class="imgleft" /><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse id est laborum.</p>
						<ul class="l1">
							<li>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </li>
							<li>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo. </li>
							<li>Duis aute irure dolor in reprehenderit in voluptate velit esse.</li>
						</ul>
						<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium.</p>
					</div><!-- END ABOUT US PAGE -->

					<div class="page"><!-- WORK PAGE -->
						<h1>Trabalhos</h1>
							<p>Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.</p>
							<div id="work">
								<ul class="work">
									<li><a href="images/work/image-1.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf1.jpg" alt="" /></a></li>
									<li><a href="images/work/image-2.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf2.jpg" alt="" /></a></li>
									<li><a href="images/work/image-3.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf3.jpg" alt="" /></a></li>
									<li><a href="images/work/image-4.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf4.jpg" alt="" /></a></li>
									<li><a href="images/work/image-5.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf5.jpg" alt="" /></a></li>
									<li><a href="images/work/image-6.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf6.jpg" alt="" /></a></li>
									<li><a href="images/work/image-7.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf7.jpg" alt="" /></a></li>
									<li><a href="images/work/image-8.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf8.jpg" alt="" /></a></li>
									<li><a href="images/work/image-9.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf9.jpg" alt="" /></a></li>
									<li><a href="images/work/image-10.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf10.jpg" alt="" /></a></li>
								</ul>
								<ul class="work">
									<li><a href="images/work/image-10.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf10.jpg" alt="" /></a></li>
									<li><a href="images/work/image-9.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf9.jpg" alt="" /></a></li>
									<li><a href="images/work/image-8.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf8.jpg" alt="" /></a></li>
									<li><a href="images/work/image-7.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf7.jpg" alt="" /></a></li>
									<li><a href="images/work/image-6.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf6.jpg" alt="" /></a></li>
									<li><a href="images/work/image-5.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf5.jpg" alt="" /></a></li>
									<li><a href="images/work/image-4.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf4.jpg" alt="" /></a></li>
									<li><a href="images/work/image-3.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf3.jpg" alt="" /></a></li>
									<li><a href="images/work/image-2.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf2.jpg" alt="" /></a></li>
									<li><a href="images/work/image-1.jpg" rel="lightbox[gallery]" title="Title Image"><img src="images/work/pf1.jpg" alt="" /></a></li>
								</ul>
							</div><!-- end work -->
							<div id="work-nav">
								<div id="prev">Prev</div>
								<div id="next">Next</div>
							</div><!-- end work-nav -->
					</div><!-- END WORK PAGE -->

					<div class="page"><!-- SOCIAL PAGE -->
						<h1>Redes Sociais</h1>
							 <ul class="social">
							   <li><img src="images/facebook.png" alt="" class="imgleft" /><span class="t1">facebook</span><br />
							    <a href="#">http://www.facebook.com/fernandosouza84</a></li>
								<li><img src="images/twitter.png" alt="" class="imgleft" /><span class="t1">twitter</span><br />
							    <a href="#">http://www.twitter.com/fernandosouza84</a></li>
								<li><img src="images/flickr.png" alt="" class="imgleft" /><span class="t1">flickr</span><br />
							    <a href="#">http://www.flickr.com/username</a></li>
								<!-- <li><img src="images/myspace.png" alt="" class="imgleft" /><span class="t1">my space</span><br />
							    <a href="#">http://www.myspace.com/fefsjoker</a></li> -->
								<!-- <li><img src="images/delicious.png" alt="" class="imgleft" /><span class="t1">delicious</span><br />
							    <a href="#">http://www.delicious.com/username</a></li> -->
								<!-- <li><img src="images/youtube.png" alt="" class="imgleft" /><span class="t1">youtube</span><br />
							    <a href="#">http://www.youtube.com/username</a></li> -->
							 </ul>
					</div><!-- END SOCIAL PAGE -->

					<div class="page"><!-- CONTACT US PAGE -->
						<h1>Entre em contato</h1>
						<div id="left-content">
							<div id="contact_form">
							  <form id="contact" action="">
								<fieldset>
								  <label for="name" id="name_label">Nome</label><br />
								  <input type="text" name="name" id="name" size="30" value="" class="text-input" />
								  <span class="error" id="name_error">Please enter name !</span><br />
								 <label for="email" id="email_label">Email</label><br />
								  <input type="text" name="email" id="email" size="30" value="" class="text-input" />
								  <span class="error" id="email_error">Please enter email address !</span>
								  <span class="error" id="email_error2">Please enter valid email address !</span><br />
								  <label for="msg" id="msg_label">Mensagem</label><br />
								 <textarea cols="25" rows="5" name="msg" id="msg" class="text-input"></textarea>
								  <span class="error" id="msg_error">Please enter message !</span>
								  <input type="submit" name="submit" class="button" id="submit_btn" value="send..."/>
								</fieldset>
							  </form>
							  </div><!-- end contact_form -->
						  </div><!-- end left-content -->

						  <div id="right-content">
						  	<!-- <strong>Address:</strong> 123 SW 34 Street, City<br />
							<strong>Phone:</strong> +1 234 56 78 90<br /> -->
							<strong>E-mail:</strong> <a href="mailto:fernando.de.souza@gmail.com">fernando.de.souza@gmail.com</a> <br /><br />

							<img src="images/map.jpg" alt="" />
						</div><!-- end right-content -->

					</div><!-- END CONTACT US PAGE -->
				</div><!-- end maincontent -->
			</div><!-- end main -->
		</div><!-- end bg-content-repeat2 -->
		</div><!-- end bg-content-repeat1 -->
		<div id="bg-content-bottom"></div><!-- end bg-content-bottom -->
	</div><!-- end content -->
	<div id="glowbottom"></div><!-- end glowbottom -->
</div>
<!-- end container -->

</body>
</html>
